name: Build and test
on:
  push:
    branches:
    - master
  pull_request:
    branches: master
env:
  CONTAINER_APP_CONTAINER_NAME: workout-tracker-api
  CONTAINER_APP_NAME: workout-tracker-api
  CONTAINER_APP_RESOURCE_GROUP_NAME: workout-tracker
  CONTAINER_REGISTRY_LOGIN_SERVER: berserkerdotnetcregistry.azurecr.io
  DOTNET_CORE_VERSION: 7.0.x
  PROJECT_NAME_FOR_DOCKER: workouttracker-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        include-prerelease: True
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Install workload
      run: dotnet workload install maui-android
    - name: Add DevExpress feed
      run: dotnet nuget add source ${{ secrets.DEVEXPRESSFEED }} -n DevExpress
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -bl
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload binlog for investigation
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: binlog
        path: msbuild.binlog